# Generated by Django 3.1.7 on 2021-07-20 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='editor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='biblioapp.editor'),
            preserve_default=False,
        ),
    ]
