# Generated by Django 3.1.7 on 2021-07-20 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioapp', '0002_book_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Description',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='book',
            name='subtitle',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.CheckConstraint(check=models.Q(release_date=datetime.date(2021, 12, 31)), name='mycustomconstraint_check1'),
        ),
    ]
