# Generated by Django 3.1.7 on 2021-07-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioapp', '0003_auto_20210720_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='imagen',
            field=models.ImageField(blank=True, default='', upload_to='portadas'),
            preserve_default=False,
        ),
    ]
