# Generated by Django 3.1.7 on 2021-07-22 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioapp', '0006_auto_20210721_0156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='email',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
    ]
