# Generated by Django 3.1.7 on 2021-07-22 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioapp', '0009_auto_20210722_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='imagen',
            new_name='image',
        ),
    ]
